name: panorama_image
description: "Display equirectangular projection panoramas with basic pan and zoom functionality"
version: 0.0.1
homepage: https://github.com/odd-io/panorama_image

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
